"""address optional in Form model

Revision ID: 610b5aece9a6
Revises: 234ed52ed10b
Create Date: 2025-10-24 12:25:28.881956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610b5aece9a6'
down_revision = '234ed52ed10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
