"""update form table

Revision ID: 61916d11651c
Revises: fd8635f571a0
Create Date: 2025-11-22 00:27:19.655980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61916d11651c'
down_revision = 'fd8635f571a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)

    # ### end Alembic commands ###
