"""links table

Revision ID: a58856c8aacc
Revises: 6945ed9347a1
Create Date: 2025-10-14 23:47:42.984910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58856c8aacc'
down_revision = '6945ed9347a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_link_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_link_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_user_id'))
        batch_op.drop_index(batch_op.f('ix_link_end_at'))
        batch_op.drop_index(batch_op.f('ix_link_created_at'))

    op.drop_table('link')
    # ### end Alembic commands ###
