"""empty message

Revision ID: d3a525e7aff3
Revises: 88e3694dce38
Create Date: 2025-10-18 12:32:24.956399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a525e7aff3'
down_revision = '88e3694dce38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_form_submitted_at'), ['submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_submitted_at'))
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###
